# This is an example Plex-MetaData's config file.

[metadata]
default-language = 'zh-Hant' # en/zh-Hant

[metadata.Amazon]
locale = 'zh_TW' # en_US, zh_TW

[metadata.AppleTVPlus]
locale = 'zh-TW' # en-US, zh-TW

[metadata.DisneyPlus]
region = 'TW' # US, TW, HK

[metadata.GooglePlay]
region = 'TW'    # US, TW
locale = 'zh-TW' # en-US, zh-TW

[metadata.Netflix]
region = 'tw' # us, tw, hk

# Default cookies dir: Plex-MetaData/cookies
#         downloads dir: Plex-MetaData/downloads
[directories]
cookies = ''
downloads = ''

# Copy user-agent from login browser (https://www.whatsmyua.info/)
[headers]
User-Agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'

[cookies]
Netflix = 'www.netflix.com_cookies.txt'

# Plex server settings
[plex]
# Method 1.
baseurl = ''
token = ''   # Finding the Token (https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/)
# Method 2.
username = ''
password = ''
servername = ''

[tmdb]
api_key = '305cd2702459761c82756596508900d7'

[proxies]
# This is a dictionary of proxies you wish to use on services that require a specific country IP.
# The dictionary key needs to be an alpha 2 country code (2-letter code, e.g. `us`, `gb`, `jp`, `de`).
# The value needs to be the proxy string which should be recognizable by python-requests and curl.
# e.g.: https://username:password123@subdomain.hostname.ext:89
# If you don't want any, just have this section blank or remove the [proxies] entirely
# us = 'http://127.0.0.1:7890' # Clash

[nordvpn]
# Like `proxies` above, this does the same thing except it automatically generates a proxy string
# for a nordvpn server automatically.
# The credentials should be `Service credentials` NOT your Nord account details!
# https://my.nordaccount.com/dashboard/nordvpn/ (Under advanced configuration).
# ex: https://support.nordvpn.com/Connectivity/Proxy/1087802472/Proxy-setup-on-qBittorrent.htm
username = ''
password = ''
