region = 'US'
language = 'en'

[endpoints]
titles = 'https://disney.content.edge.bamgrid.com/svc/content/{content_type}/version/5.1/region/{region}/audience/k-false,l-true/maturity/1850/language/{language}/{encoded_type}/{content_id}'
episodes = 'https://disney.content.edge.bamgrid.com/svc/content/DmcEpisodes/version/5.1/region/{region}/audience/k-false,l-true/maturity/1850/language/{language}/seasonId/{season_id}/pageSize/30/page/{page_number}'
